_target_: cross_view_transformer.model.autoencoder.AutoEncoder

dim: 256
dim_last: 64
label_indices: [0,0,0] # [[4, 5, 6, 7, 8, 10, 11,12],[9]]

decoder:
  _target_: cross_view_transformer.model.decoder.Decoder

  dim: ${model.dim}
  blocks: [256,128,64]
  residual: True
  factor: 2
  