_target_: cross_view_transformer.model.sparsebev_seg.SparseBEVSeg

backbone:
  # _target_: cross_view_transformer.model.backbones.efficientnet.EfficientNet_PointBEV
  _target_: cross_view_transformer.model.backbones.timm_backbones.TimmBackbone

  model_name: resnet50 # efficientnet_b4
  out_indices: [1,2,3,4]
  fpn: True
  embed_dims: ${model.encoder.embed_dims}

  freeze_layers: [layer1]

  image_height: ${data.image.h}
  image_width: ${data.image.w}

# neck:
#   _target_: cross_view_transformer.model.backbones.agp.AGPNeck

#   align_res_layer:
#     _target_: cross_view_transformer.model.backbones.agp.AlignRes
#     mode: "upsample"
#     scale_factors: [1, 2]

#   prepare_c_layer:
#     _target_: cross_view_transformer.model.backbones.agp.PrepareChannel

#     in_channels: [56, 160]
#     mode: "doubleconv"
#     tail_mode: "conv2d"
  
#   list_output: True

encoder:
  _target_: cross_view_transformer.model.sparsebev_seg.SparseHead

  embed_dims: 128

  # bev
  num_points_in_pillar: 8
  H: 200
  W: 200
  Z: 8

  transformer:
    _target_: cross_view_transformer.model.sparsebev_seg.SparseBEVTransformerDecoder
    
    n_layer: 1

    num_points_in_pillar: ${model.encoder.num_points_in_pillar}
    embed_dims: ${model.encoder.embed_dims}
    pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
    num_levels: 1
    h: ${data.image.h}
    w: ${data.image.w}
    num_points: 8
    checkpointing: False
    num_groups: 1
    scale: 1.0

decoder:
  _target_: cross_view_transformer.model.decoder.SimpleBEVDecoder
  in_channels: 128

head:
  _target_: cross_view_transformer.model.decoder.SegHead

  dim_last: 128
  multi_head: True
  # decoder:
    # _target_: cross_view_transformer.model.decoder.BEVDecoder
    
    # dim: ${model.encoder.embed_dims}
    # blocks: [128, 128]
    # residual: True
    # factor: 2
    # _target_: cross_view_transformer.model.decoder.SimpleBEVDecoder
    # in_channels: ${model.encoder.embed_dims}

  outputs:
    bev: [0, 1]
    ped: [1, 2]

box_encoder_type: bev

box_encoder:
  # BEVFormer
  _target_: cross_view_transformer.model.detr.BEVFormer.BEVFomerHead

  transformer:
    _target_: cross_view_transformer.model.detr.BEVFormer.DetectionTransformerDecoder

    n_layer: 4
    embed_dims: ${model.encoder.embed_dims}
    nheads: 4

  embed_dims: ${model.encoder.embed_dims}
  num_classes: 8
  num_query: 400
  num_reg_fcs: 2
  pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
  box_3d: ${data.box_3d}

  # SparseBEV
  # _target_: cross_view_transformer.model.sparsebev.SparseHead

  # embed_dims: 128
  # query_type: box

  # # box
  # pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
  # num_classes: 8
  # num_query: 400
  # num_reg_fcs: 2
  # num_points_in_pillar: 1

  # transformer:
  #   _target_: cross_view_transformer.model.sparsebev.SparseBEVTransformerDecoder
    
  #   n_layer: 4

  #   num_points_in_pillar: ${model.encoder.num_points_in_pillar}
  #   embed_dims: ${model.encoder.embed_dims}
  #   pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
  #   num_levels: 4
  #   h: ${data.image.h}
  #   w: ${data.image.w}
  #   num_points: 16
  #   checkpointing: True
  #   query_type: box
  #   num_groups: 1
  
  # Detr3D
  # _target_: cross_view_transformer.model.detr.detr3d_transformer.Detr3DHead

  # with_box_refine: True
  # as_two_stage: False
  # num_query: 80
  # embed_dims: 128
  # num_classes: 8
  # pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
  # orientation: False
  
  # transformer:
  #   _target_: cross_view_transformer.model.detr.detr3d_transformer.Detr3DTransformer
    
  #   embed_dims: 128
  #   num_feature_levels: 4
  #   num_cams: 6
  #   # two_stage_num_proposals: 80

  #   decoder:
  #     _target_: cross_view_transformer.model.detr.detr3d_transformer.Detr3DTransformerDecoder

  #     n_layer: 4
  #     return_intermediate: True

  #     d_model: 128
  #     nhead: 4
  #     dim_feedforward: 512
  #     pc_range: [-49.75, -49.75, -3.375, 49.75, 49.75, 5.375]
  #     num_levels: 4
  #     h: ${data.image.h}
  #     w: ${data.image.w}
  #     num_points: 1