ped_weight: 10.0
ped:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[9]]
  gamma: 2.0
  alpha: 0.75
  key: ped

visible_weight: 5.0
visible:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0

# center_weight: 0.0
# center:
#   _target_: cross_view_transformer.losses.CenterLoss

#   gamma: 2.0
#   min_visibility: 2

STATIC_weight: 0.1
STATIC:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[0,1]]
  gamma: 2.0
  alpha: -1.0
  key: STATIC

DIVIDER_weight: 1.0
DIVIDER:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[2,3]]
  gamma: 2.0
  alpha: -1.0
  key: DIVIDER

CROSSING_weight: 1.0
CROSSING:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[12]]
  gamma: 2.0
  alpha: -1.0
  key: CROSSING

WALKWAY_weight: 1.0
WALKWAY:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[13]]
  gamma: 2.0
  alpha: -1.0
  key: WALKWAY

CARPARK_weight: 1.0
CARPARK:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[14]]
  gamma: 2.0
  alpha: -1.0
  key: CARPARK

# pedDice_weight: 0.1
# pedDice:
#   _target_: cross_view_transformer.losses.diceLoss

#   label_indices: [[9]]
#   min_visibility: 2
#   key: ped

# visibleDice_weight: 0.1
# visibleDice:
#   _target_: cross_view_transformer.losses.diceLoss

#   label_indices: ${data.label_indices}
#   min_visibility: 2