CE_weight: 1.0
CE:
  _target_: cross_view_transformer.losses.segmentationLoss

  min_visibility: 2

center_weight: 0.1
center:
  _target_: cross_view_transformer.losses.CenterLoss

  gamma: 2.0
  min_visibility: 2