ped_weight: 20.0
ped:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[9]]
  gamma: 2.0
  alpha: -1.0
  # min_visibility: 2
  key: ped
  sparse: ${model.sparse}

visible_weight: 10.0
visible:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  # min_visibility: 2
  sparse: ${model.sparse}

Set:
  _target_: cross_view_transformer.set_loss.SetCriterion

  num_classes: ${model.box_encoder.num_classes}
  matcher: 
    _target_: cross_view_transformer.matcher.HungarianMatcher
  
  weight_dict: 
    labels: 0.1
    boxes: 0.1
  eos_coef: 0.1
  losses: ['labels', 'boxes']

loss_ce_weight: 0.001 # 0.02
loss_bbox_weight: 0.005 # 0.1
# loss_giou_weight: 2.0
class_error_weight: 0.0
aux_weight: 0.001