ped_weight: 1.0
ped:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[9]]
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2
  key: ped

center_weight: 1.0
center:
  _target_: cross_view_transformer.losses.SpatialRegressionLoss

  norm: 2

offset_weight: 0.01
offset:
  _target_: cross_view_transformer.losses.SpatialRegressionLoss

  norm: 1

vehicle_weight: 1.0
vehicle:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2
  key: vehicle