ped_weight: 2.0
ped:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[9]]
  gamma: 2.0
  alpha: 0.66
  # min_visibility: 2
  key: ped

visible_weight: 1.0
visible:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  # min_visibility: 2
