ped_weight: 2.0
ped:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: [[9]]
  gamma: 2.0
  alpha: 0.75
  # min_visibility: 2
  key: ped

visible_weight: 1.0
visible:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  # min_visibility: 2

Set:
  _target_: cross_view_transformer.set_loss.SetCriterion

  num_classes: 8
  matcher: 
    _target_: cross_view_transformer.matcher.HungarianMatcher

    cost_class: ${loss.loss_ce_weight}
    cost_bbox: ${loss.loss_bbox_weight}
  
  weight_dict: 
    labels: 0.1
    boxes: 0.1
    
  eos_coef: 0.1
  aux_weight: 0.1
  losses: ['labels', 'boxes']

loss_ce_weight: 0.01 # 0.02
loss_bbox_weight: 0.05 # 0.1
# loss_giou_weight: 2.0
class_error_weight: 0.0