center_weight: 2.0
center:
  _target_: cross_view_transformer.losses.SeqSegmentationLoss

  mode: "l2"
  # min_visibility: 2
  key: center

offset_weight: 0.1
offset:
  _target_: cross_view_transformer.losses.SeqSegmentationLoss

  mode: "l1"
  # min_visibility: 2
  # ignore_index: 0.0
  key: offset

visible_weight: 1.0
visible:
  _target_: cross_view_transformer.losses.SeqSegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  key: VEHICLE
  mode: "sigmoid"
  # min_visibility: 2
