center_weight: 0.1
center:
  _target_: cross_view_transformer.losses.SpatialRegressionLoss

  norm: 2
  min_visibility: 2


offset_weight: 0.1
offset:
  _target_: cross_view_transformer.losses.SpatialRegressionLoss

  norm: 1
  min_visibility: 2
  ignore_index: 0.0

visible_weight: 1.0
visible:
  _target_: cross_view_transformer.losses.BinarySegmentationLoss

  label_indices: ${data.label_indices}
  gamma: 2.0
  alpha: -1.0
  min_visibility: 2
